# Specify version of docker-compose for backwards compatability
version: '3.8'

# Define services (docker containers) to run
services:

  streamlit-app:
    build: ./02_app_requirements
    restart: always
    ports:
      - '8502:8501'
    volumes:
      - ${PWD}:/app