# Define services (docker containers) to run
services:
  # Define jupyter lab
  dev_jupyter:
    build: ./01_dev_requirements
    environment:
      - JUPYTER_TOKEN=
      - GRANT_SUDO=yes
    restart: always
    ports:
      - '10000:8888' # Port to access notebook
      - '4040:4040'  # Port to access SparkUI
    volumes:
      - ${PWD}:/home/jovyan/work

  dev_app:
    build: ./02_app_requirements
    restart: always
    ports:
      - '8501:8501'
    volumes:
      - ${PWD}:/app