# Specify version of docker-compose for backwards compatability
version: '3.8'

# Define services (docker containers) to run
services:
  app:
    build: .
    ports:
      - '8502:8501'
    volumes:
      - ${PWD}:/app